package segana;
// Generated Mar 13, 2012 4:29:28 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Acesso generated by hbm2java
 */
@Entity
@Table(name="acesso"
    ,catalog="gana"
)
public class Acesso  implements java.io.Serializable {


     private int idacesso;
     private Opcion opcion;
     private Rol rol;

    public Acesso() {
    }

    public Acesso(int idacesso, Opcion opcion, Rol rol) {
       this.idacesso = idacesso;
       this.opcion = opcion;
       this.rol = rol;
    }
   
     @Id 
    
    @Column(name="idacesso", unique=true, nullable=false)
    public int getIdacesso() {
        return this.idacesso;
    }
    
    public void setIdacesso(int idacesso) {
        this.idacesso = idacesso;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="opcion_idopcion", nullable=false)
    public Opcion getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(Opcion opcion) {
        this.opcion = opcion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rol_idrol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


