package segana;
// Generated Mar 13, 2012 4:29:28 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Encuentro generated by hbm2java
 */
@Entity
@Table(name="encuentro"
    ,catalog="gana"
)
public class Encuentro  implements java.io.Serializable {


     private int idencuentro;
     private Edicion edicion;
     private Equipo equipoByEquipoIdequipo;
     private Equipo equipoByEquipoIdequipo1;
     private String escenario;
     private Date fecha;
     private Set<Apuesta> apuestas = new HashSet<Apuesta>(0);

    public Encuentro() {
    }

	
    public Encuentro(int idencuentro, Edicion edicion, Equipo equipoByEquipoIdequipo, Equipo equipoByEquipoIdequipo1) {
        this.idencuentro = idencuentro;
        this.edicion = edicion;
        this.equipoByEquipoIdequipo = equipoByEquipoIdequipo;
        this.equipoByEquipoIdequipo1 = equipoByEquipoIdequipo1;
    }
    public Encuentro(int idencuentro, Edicion edicion, Equipo equipoByEquipoIdequipo, Equipo equipoByEquipoIdequipo1, String escenario, Date fecha, Set<Apuesta> apuestas) {
       this.idencuentro = idencuentro;
       this.edicion = edicion;
       this.equipoByEquipoIdequipo = equipoByEquipoIdequipo;
       this.equipoByEquipoIdequipo1 = equipoByEquipoIdequipo1;
       this.escenario = escenario;
       this.fecha = fecha;
       this.apuestas = apuestas;
    }
   
     @Id 
    
    @Column(name="idencuentro", unique=true, nullable=false)
    public int getIdencuentro() {
        return this.idencuentro;
    }
    
    public void setIdencuentro(int idencuentro) {
        this.idencuentro = idencuentro;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="edicion_idedicion", nullable=false)
    public Edicion getEdicion() {
        return this.edicion;
    }
    
    public void setEdicion(Edicion edicion) {
        this.edicion = edicion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="equipo_idequipo", nullable=false)
    public Equipo getEquipoByEquipoIdequipo() {
        return this.equipoByEquipoIdequipo;
    }
    
    public void setEquipoByEquipoIdequipo(Equipo equipoByEquipoIdequipo) {
        this.equipoByEquipoIdequipo = equipoByEquipoIdequipo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="equipo_idequipo1", nullable=false)
    public Equipo getEquipoByEquipoIdequipo1() {
        return this.equipoByEquipoIdequipo1;
    }
    
    public void setEquipoByEquipoIdequipo1(Equipo equipoByEquipoIdequipo1) {
        this.equipoByEquipoIdequipo1 = equipoByEquipoIdequipo1;
    }
    
    @Column(name="escenario", length=150)
    public String getEscenario() {
        return this.escenario;
    }
    
    public void setEscenario(String escenario) {
        this.escenario = escenario;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="encuentro")
    public Set<Apuesta> getApuestas() {
        return this.apuestas;
    }
    
    public void setApuestas(Set<Apuesta> apuestas) {
        this.apuestas = apuestas;
    }




}


