package segana;
// Generated Mar 13, 2012 4:29:28 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Equipo generated by hbm2java
 */
@Entity
@Table(name="equipo"
    ,catalog="gana"
)
public class Equipo  implements java.io.Serializable {


     private int idequipo;
     private String nombre;
     private Integer rankin;
     private Date fundacion;
     private Set<Participacion> participacions = new HashSet<Participacion>(0);
     private Set<Pronostico> pronosticos = new HashSet<Pronostico>(0);
     private Set<Encuentro> encuentrosForEquipoIdequipo = new HashSet<Encuentro>(0);
     private Set<Encuentro> encuentrosForEquipoIdequipo1 = new HashSet<Encuentro>(0);

    public Equipo() {
    }

	
    public Equipo(int idequipo) {
        this.idequipo = idequipo;
    }
    public Equipo(int idequipo, String nombre, Integer rankin, Date fundacion, Set<Participacion> participacions, Set<Pronostico> pronosticos, Set<Encuentro> encuentrosForEquipoIdequipo, Set<Encuentro> encuentrosForEquipoIdequipo1) {
       this.idequipo = idequipo;
       this.nombre = nombre;
       this.rankin = rankin;
       this.fundacion = fundacion;
       this.participacions = participacions;
       this.pronosticos = pronosticos;
       this.encuentrosForEquipoIdequipo = encuentrosForEquipoIdequipo;
       this.encuentrosForEquipoIdequipo1 = encuentrosForEquipoIdequipo1;
    }
   
     @Id 
    
    @Column(name="idequipo", unique=true, nullable=false)
    public int getIdequipo() {
        return this.idequipo;
    }
    
    public void setIdequipo(int idequipo) {
        this.idequipo = idequipo;
    }
    
    @Column(name="nombre", length=150)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="rankin")
    public Integer getRankin() {
        return this.rankin;
    }
    
    public void setRankin(Integer rankin) {
        this.rankin = rankin;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fundacion", length=10)
    public Date getFundacion() {
        return this.fundacion;
    }
    
    public void setFundacion(Date fundacion) {
        this.fundacion = fundacion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="equipo")
    public Set<Participacion> getParticipacions() {
        return this.participacions;
    }
    
    public void setParticipacions(Set<Participacion> participacions) {
        this.participacions = participacions;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="equipo")
    public Set<Pronostico> getPronosticos() {
        return this.pronosticos;
    }
    
    public void setPronosticos(Set<Pronostico> pronosticos) {
        this.pronosticos = pronosticos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="equipoByEquipoIdequipo")
    public Set<Encuentro> getEncuentrosForEquipoIdequipo() {
        return this.encuentrosForEquipoIdequipo;
    }
    
    public void setEncuentrosForEquipoIdequipo(Set<Encuentro> encuentrosForEquipoIdequipo) {
        this.encuentrosForEquipoIdequipo = encuentrosForEquipoIdequipo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="equipoByEquipoIdequipo1")
    public Set<Encuentro> getEncuentrosForEquipoIdequipo1() {
        return this.encuentrosForEquipoIdequipo1;
    }
    
    public void setEncuentrosForEquipoIdequipo1(Set<Encuentro> encuentrosForEquipoIdequipo1) {
        this.encuentrosForEquipoIdequipo1 = encuentrosForEquipoIdequipo1;
    }




}


