package segana;
// Generated Mar 13, 2012 4:29:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Opcion generated by hbm2java
 */
@Entity
@Table(name="opcion"
    ,catalog="gana"
)
public class Opcion  implements java.io.Serializable {


     private int idopcion;
     private Modulo modulo;
     private String titulo;
     private String descripcion;
     private String link;
     private Integer orden;
     private Set<Acesso> acessos = new HashSet<Acesso>(0);

    public Opcion() {
    }

	
    public Opcion(int idopcion, Modulo modulo) {
        this.idopcion = idopcion;
        this.modulo = modulo;
    }
    public Opcion(int idopcion, Modulo modulo, String titulo, String descripcion, String link, Integer orden, Set<Acesso> acessos) {
       this.idopcion = idopcion;
       this.modulo = modulo;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.link = link;
       this.orden = orden;
       this.acessos = acessos;
    }
   
     @Id 
    
    @Column(name="idopcion", unique=true, nullable=false)
    public int getIdopcion() {
        return this.idopcion;
    }
    
    public void setIdopcion(int idopcion) {
        this.idopcion = idopcion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modulo_idmodulo", nullable=false)
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    
    @Column(name="titulo", length=45)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    
    @Column(name="descripcion", length=245)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="link", length=345)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    
    @Column(name="orden")
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="opcion")
    public Set<Acesso> getAcessos() {
        return this.acessos;
    }
    
    public void setAcessos(Set<Acesso> acessos) {
        this.acessos = acessos;
    }




}


