package segana;
// Generated Mar 13, 2012 4:29:28 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Participacion generated by hbm2java
 */
@Entity
@Table(name="participacion"
    ,catalog="gana"
)
public class Participacion  implements java.io.Serializable {


     private int idparticipacion;
     private Edicion edicion;
     private Equipo equipo;

    public Participacion() {
    }

    public Participacion(int idparticipacion, Edicion edicion, Equipo equipo) {
       this.idparticipacion = idparticipacion;
       this.edicion = edicion;
       this.equipo = equipo;
    }
   
     @Id 
    
    @Column(name="idparticipacion", unique=true, nullable=false)
    public int getIdparticipacion() {
        return this.idparticipacion;
    }
    
    public void setIdparticipacion(int idparticipacion) {
        this.idparticipacion = idparticipacion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="edicion_idedicion", nullable=false)
    public Edicion getEdicion() {
        return this.edicion;
    }
    
    public void setEdicion(Edicion edicion) {
        this.edicion = edicion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="equipo_idequipo", nullable=false)
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }




}


