package segana;
// Generated Mar 13, 2012 4:29:28 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pronostico generated by hbm2java
 */
@Entity
@Table(name="pronostico"
    ,catalog="gana"
)
public class Pronostico  implements java.io.Serializable {


     private int idpronostico;
     private Equipo equipo;
     private Apuesta apuesta;
     private Integer valor;

    public Pronostico() {
    }

	
    public Pronostico(int idpronostico, Equipo equipo, Apuesta apuesta) {
        this.idpronostico = idpronostico;
        this.equipo = equipo;
        this.apuesta = apuesta;
    }
    public Pronostico(int idpronostico, Equipo equipo, Apuesta apuesta, Integer valor) {
       this.idpronostico = idpronostico;
       this.equipo = equipo;
       this.apuesta = apuesta;
       this.valor = valor;
    }
   
     @Id 
    
    @Column(name="idpronostico", unique=true, nullable=false)
    public int getIdpronostico() {
        return this.idpronostico;
    }
    
    public void setIdpronostico(int idpronostico) {
        this.idpronostico = idpronostico;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="equipo_idequipo", nullable=false)
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="apuesta_idapuesta", nullable=false)
    public Apuesta getApuesta() {
        return this.apuesta;
    }
    
    public void setApuesta(Apuesta apuesta) {
        this.apuesta = apuesta;
    }
    
    @Column(name="valor")
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }




}


