package segana;
// Generated Mar 13, 2012 4:29:28 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rolusuario generated by hbm2java
 */
@Entity
@Table(name="rolusuario"
    ,catalog="gana"
)
public class Rolusuario  implements java.io.Serializable {


     private int idrolusuario;
     private Rol rol;
     private Usuario usuario;

    public Rolusuario() {
    }

    public Rolusuario(int idrolusuario, Rol rol, Usuario usuario) {
       this.idrolusuario = idrolusuario;
       this.rol = rol;
       this.usuario = usuario;
    }
   
     @Id 
    
    @Column(name="idrolusuario", unique=true, nullable=false)
    public int getIdrolusuario() {
        return this.idrolusuario;
    }
    
    public void setIdrolusuario(int idrolusuario) {
        this.idrolusuario = idrolusuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rol_idrol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idusuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


