package segana;
// Generated Mar 13, 2012 4:29:28 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name="tarjeta"
    ,catalog="gana"
)
public class Tarjeta  implements java.io.Serializable {


     private int idtarjeta;
     private Usuario usuario;
     private String descripcion;
     private Date fechaVence;
     private String nombre;

    public Tarjeta() {
    }

	
    public Tarjeta(int idtarjeta, Usuario usuario) {
        this.idtarjeta = idtarjeta;
        this.usuario = usuario;
    }
    public Tarjeta(int idtarjeta, Usuario usuario, String descripcion, Date fechaVence, String nombre) {
       this.idtarjeta = idtarjeta;
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.fechaVence = fechaVence;
       this.nombre = nombre;
    }
   
     @Id 
    
    @Column(name="idtarjeta", unique=true, nullable=false)
    public int getIdtarjeta() {
        return this.idtarjeta;
    }
    
    public void setIdtarjeta(int idtarjeta) {
        this.idtarjeta = idtarjeta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idusuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="descripcion", length=145)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_vence", length=10)
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }
    
    @Column(name="nombre", length=75)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


