package segana;
// Generated Mar 13, 2012 4:29:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Torneo generated by hbm2java
 */
@Entity
@Table(name="torneo"
    ,catalog="gana"
)
public class Torneo  implements java.io.Serializable {


     private int idtorneo;
     private Deporte deporte;
     private String nombre;
     private int edicionIdedicion;
     private Set<Edicion> edicions = new HashSet<Edicion>(0);

    public Torneo() {
    }

	
    public Torneo(int idtorneo, Deporte deporte, int edicionIdedicion) {
        this.idtorneo = idtorneo;
        this.deporte = deporte;
        this.edicionIdedicion = edicionIdedicion;
    }
    public Torneo(int idtorneo, Deporte deporte, String nombre, int edicionIdedicion, Set<Edicion> edicions) {
       this.idtorneo = idtorneo;
       this.deporte = deporte;
       this.nombre = nombre;
       this.edicionIdedicion = edicionIdedicion;
       this.edicions = edicions;
    }
   
     @Id 
    
    @Column(name="idtorneo", unique=true, nullable=false)
    public int getIdtorneo() {
        return this.idtorneo;
    }
    
    public void setIdtorneo(int idtorneo) {
        this.idtorneo = idtorneo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="deporte_iddeporte", nullable=false)
    public Deporte getDeporte() {
        return this.deporte;
    }
    
    public void setDeporte(Deporte deporte) {
        this.deporte = deporte;
    }
    
    @Column(name="nombre", length=150)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="edicion_idedicion", nullable=false)
    public int getEdicionIdedicion() {
        return this.edicionIdedicion;
    }
    
    public void setEdicionIdedicion(int edicionIdedicion) {
        this.edicionIdedicion = edicionIdedicion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="torneo")
    public Set<Edicion> getEdicions() {
        return this.edicions;
    }
    
    public void setEdicions(Set<Edicion> edicions) {
        this.edicions = edicions;
    }




}


